- name: "update all packages"
  hosts: localhost
  connection: local
  tasks:
    - name: specific mirror because some have old packages
      community.general.ini_file:
        path: /etc/yum.repos.d/almalinux-baseos.repo
        section: baseos
        option: baseurl
        value: "https://almalinux.mirror.liteserver.nl/$releasever/BaseOS/x86_64/os"
        state: present
    - name: disable repo mirrors for AlmaLinux baseos
      community.general.ini_file:
        path: /etc/yum.repos.d/almalinux-baseos.repo
        section: baseos
        option: mirrorlist
        value: "https://mirrors.almalinux.org/mirrorlist/$releasever/baseos"
        state: absent
    - name: install updates
      ansible.builtin.dnf:
        name: "*"
        exclude:
          - rubygem-redis
        state: latest
    - name: Enable Puppet Tools Release repo
      ansible.builtin.dnf:
        disable_gpg_check: true
        name: 
          - 'https://yum.puppetlabs.com/puppet-tools-release-el-9.noarch.rpm'
          - 'https://yum.puppetlabs.com/puppet-release-el-9.noarch.rpm'
          - 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm'
          - 'https://yum.theforeman.org/releases/3.10/el9/x86_64/foreman-release.rpm'
        state: present
    - name: Enable extra repositories
      ansible.builtin.command:
        cmd: dnf config-manager --set-enabled crb
    - name: Open firewall ports
      ansible.posix.firewalld:
        permanent: yes
        immediate: yes
        port: "{{item.port}}/{{item.proto}}"
        state: enabled
      with_items:
        - {port: "80", proto: "tcp" }
        - {port: "443", proto: "tcp"}
        - {port: "69", proto: "udp"}
        - {port: "8140", proto: "tcp"}
    - name: Install foreman packages
      ansible.builtin.dnf:
        state: present
        name:
          - foreman-installer
          - epel-release
          - elrepo-release
          - foreman-libvirt
          - foreman-plugin
          - foreman-vmware
          - foreman-console
          - foreman-cli
          - foreman-ec2
          - foreman-proxy
    - name: Setup Foreman installer
      ansible.builtin.command:
        cmd: foreman-installer
      register: foremanconfig
    - name: Show foreman-installer result
      ansible.builtin.debug:
        msg: '{{ foremanconfig }}'
    - name: Save foreman config in local file
      ansible.builtin.copy:
        dest: foremanconfig.txt
        content: "{{ foremanconfig.stdout_lines }}"

